Add missing include for memcopy and strlen
Otherwise, compiling with clang produces the following errors:

  error: use of undeclared identifier 'memcpy'; did you mean 'wmemcpy'?

  error: use of undeclared identifier 'strlen'