Fix missing include
When compiling with Visual Studio 16.9.4, I get the following errors:

    D:\dev\cpp-sqlitelib\sqlitelib.h(186,1): error C2061: syntax error:
    identifier 'shared_ptr'

    D:\dev\cpp-sqlitelib\sqlitelib.h(271,8): error C2039: 'shared_ptr':
    is not a member of 'std'